#!/bin/bash
# Name- Gurleen Kaur
# Student Number- 200522530
# Section -1
# System Information
system_report=" System Report generated by $(whoami), $(date)"
system_info="---------------------
System Information
---------------------
Hostname: $(hostname)"
os_info="OS: $(source /etc/os-release && echo $PRETTY_NAME)"
uptime_info="Uptime: $(uptime -p)"
# Section -2
# Hardware Information
hardware_info="Hardware Information"
cpu_info="CPU: $(lscpu | grep 'Model name' | awk -F': ' '{print $2}')"
speed_info="Speed: $(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /size:/{print $2; exit}')"
max_speed_info="MAX Speed: $(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /capacity:/{print $2; exit}')"
ram_info="RAM: $(sudo lshw -short -C memory | grep -i 'system memory' | awk '{print $3}')"
disk_info="Disks: $(lsblk --output NAME,SIZE,TYPE,MOUNTPOINT,LABEL --exclude 7 | awk '!/loop/ {printf "%-8s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3, $4, $5, $6}')"
video_card_info="Video card: $(lspci -nnk | grep -i 'VGA' | awk -F': ' '{print $2}' | uniq)"

# section -3
# Network Information
network_info="Network Information"
fqdn_info="FQDN: $(hostname -f)"
host_address_info="Host Address: $(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')"
gateway_ip_info="Gateway IP: $(ip r | awk '/default/ {print $3}')"
dns_server_info="DNS Server: $(grep -E '^nameserver' /etc/resolv.conf | awk '{print $2}')"
network_interface_info="$(sudo lshw -class network | grep -E 'description|product|vendor|physical id|logical name' | awk -F ':' '{print $1 ": " $2}')"
ip_address_info="IP Address: $(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')"

# section -4
# System Status
system_status="System Status"
users_info="Users Logged In: $(who | awk '{print $1}' | sort | uniq | paste -s -d ',')"
disk_space_info="Disk Space:\n$(df -h)"
process_count_info="Process Count: $(ps -e | wc -l)"
load_averages_info="Load Averages: $(uptime | awk -F'[a-z]:' '{print $2}')"
memory_allocation_info="$(free -h | awk '/^Mem:/ {print "Type\tTotal\tAvailable"; print $1 "\t" $2 "\t" $7}')"
listening_ports_info="$(ss -tuln | awk 'BEGIN {print "State\tRecv-Q\tSend-Q\tLocal Address:Port\tPeer Address:Port"} /LISTEN/ {print $1 "\t" $2 "\t" $3 "\t" $4 "\t\t" $5}')"
ufw_rules_info="(UFW Rules: $(sudo ufw status numbered | grep -v 'Status: active')"


# after making all variables, use echo to give outputs.
# Output the system report
echo "$system_report"

# Output system information
echo "$system_info"
echo "$os_info"
echo "$uptime_info"
echo "---------------------"
# Output hardware information
echo "$hardware_info"
echo "---------------------"
echo "$cpu_info"
echo "$speed_info"
echo "$max_speed_info"
echo "$ram_info"
echo "$disk_info"
echo "$video_card_info"
echo "---------------------"
# Output network information
echo "$network_info"
echo "---------------------"
echo "$fqdn_info"
echo "$host_address_info"
echo "$gateway_ip_info"
echo "$dns_server_info"
echo "Network Interface Information:"
echo "$network_interface_info"
echo "$ip_address_info"

# Output system status
echo "$system_status"
echo "$users_info"
echo "$disk_space_info"
echo "$process_count_info"
echo "$load_averages_info"
echo -e "Memory Allocation:\n$memory_allocation_info"
echo -e "Listening Network Ports:\n$listening_ports_info"
echo "$ufw_rules_info"
# End.